import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Administrador",
      image: "/imgUser/user (1).jpg",
      lastName: "Local",
      email: "admin@example.com",
      password: bcrypt.hashSync("GameOn2022!"),
      isAdmin: true,
    },
    {
      name: "Administrador",
      image: "/imgUser/user (2).jpg",
      lastName: "Online",
      email: "admin2@example.com",
      password: bcrypt.hashSync("GameOn2022!"),
      isAdmin: true,
    },
    {
      name: "Usuário",
      image: "/imgUser/user (3).jpg",
      lastName: "Local",
      email: "user@example.com",
      password: bcrypt.hashSync("GameOn2022!"),
      isAdmin: false,
    },
    {
      name: "Usuário",
      image: "/imgUser/user (4).jpg",
      lastName: "Online",
      email: "user2@example.com",
      password: bcrypt.hashSync("GameOn2022!"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Halo Infinite",
      image: "/img/game (1).jpg",
      slug: "halo-infinite",
      title: "Título do game",
      category: "Xbox",
      price: 250.0,
      description:
        "O lendário super soldado retorna em Halo Infinite. A 343 Industries e a Microsoft estão construindo o maior e mais visualmente espetacular Halo até agora. Halo Infinite estreia na família de consoles Xbox, incluindo o Xbox Series X, o console de jogos mais recente e poderoso da Microsoft. Para aproveitar ao máximo sua prodigiosa proeza gráfica, a 343 Industries construiu um mecanismo de jogo totalmente novo e de última geração, dando a seus artistas de classe mundial as ferramentas e a tecnologia para realizar os mundos, a guerra e a maravilha do universo Halo em um estilo sem precedentes e fidelidade. A 343 Industries deu à Dark Horse acesso à arte e aos artistas que trouxeram Halo Infinite à vida vibrante e vívida. Está tudo aqui em detalhes incomparáveis, os heróis que você aprendeu a amar - o Master Chief, os bravos soldados da UNSC, bem como as armas, veículos, vilões e vistas - e, claro, os ambientes homônimos e magníficos do próprio Halo.",
      rating: 4.5,
      numReviews: 10,
      countInStock: 1,
      publisher: "343 e Microsoft",
      gender: "Ação",
      sellCount: 0,
    },
    {
      name: "Gears 5",
      image: "/img/Gears-5.jpeg",
      slug: "gears-5",
      title: "Operação cinco",
      category: "Xbox",
      price: 300.0,
      description: "De uma das sagas mais aclamadas do game, o Gears 5, desenvolvido pela Microsoft para Xbox One e Xbox Series, está maior do que nunca, com cinco modos emocionantes e uma campanha ainda mais intensa. Com uma guerra descendo, Kait Diaz se liberta para descobrir sua conexão com o inimigo e descobre o verdadeiro perigo para a Sera – ela mesma.Possui recursos como: - Tours of Duty: Aumente sua classificação de novo recruta para general quatro estrelas em Gears Tours of Duty. Enfrente desafios novos e empolgantes, ganhe recompensas incríveis e mostre sua carteira.- Boot Camp: Novo no Gears ou apenas um pouco enferrujado? Bootcamp é uma maneira divertida de aprender as regras, desde o básico até técnicas de combate avançadas.- Jogue como Jack, seu bot de suporte voador individual que pode proteger aliados e atingir os inimigos, perfeito para jogadores novos no Gears.",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      publisher: "Nintendo",
      gender: "FPS",
      sellCount: 0,
    },
    {
      name: "Game 3",
      image: "/img/game (3).jpeg",
      slug: "Game-03",
      title: "Título do game",
      category: "PlayStation",
      price: 200.0,
      description: "É um Game incrível",
      rating: 4.5,
      numReviews: 10,
      countInStock: 7,
      publisher: "Eletronic Arts",
      gender: "Ação",
      sellCount: 0,
    },
    {
      name: "Game 4",
      image: "/img/game (4).jpeg",
      slug: "Game-04",
      title: "Título do game",
      category: "PlayStation",
      price: 190.0,
      description: "É um Game incrível",
      rating: 4.5,
      numReviews: 10,
      countInStock: 3,
      publisher: "Rockstar Games",
      gender: "Ação",
      sellCount: 0,
    },
    {
      name: "Game 5",
      image: "/img/game (5).jpeg",
      slug: "Game-05",
      title: "Título do game",
      category: "Xbox",
      price: 160.0,
      description: "É um Game incrível",
      rating: 4.5,
      numReviews: 10,
      countInStock: 2,
      publisher: "Rockstar Games",
      gender: "Ação",
      sellCount: 0,
    },
    {
      name: "Game 6",
      image: "/img/game (6).jpeg",
      slug: "Game-06",
      title: "Título do game",
      category: "Xbox",
      price: 150.0,
      description: "É um Game incrível",
      rating: 4.5,
      numReviews: 10,
      countInStock: 8,
      publisher: "Sony",
      gender: "Ação",
      sellCount: 0,
    },
    {
      name: "Game 7",
      image: "/img/game (7).jpeg",
      slug: "Game-07",
      title: "Título do game",
      category: "Xbox",
      price: 140.0,
      description: "É um Game incrível",
      rating: 4.5,
      numReviews: 10,
      countInStock: 0,
      publisher: "Eletronic Arts",
      gender: "Ação",
      sellCount: 0,
    },
    {
      name: "Game 8",
      image: "/img/game (8).jpeg",
      slug: "Game-08",
      title: "Título do game",
      category: "Xbox",
      price: 160.0,
      description: "É um Game incrível",
      rating: 4.5,
      numReviews: 10,
      countInStock: 0,
      publisher: "Eletronic Arts",
      gender: "Ação",
      sellCount: 0,
    },
    {
      name: "Game 9",
      image: "/img/game (9).jpeg",
      slug: "Game-09",
      title: "Título do game",
      category: "Xbox",
      price: 120.0,
      description: "É um Game incrível",
      rating: 4.5,
      numReviews: 10,
      countInStock: 1,
      publisher: "Eletronic Arts",
      gender: "Ação",
      sellCount: 0,
    },
  ],
};

export default data;
