import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Index.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.index}>
        <h1>Olá mundo</h1>
      </main>
    </div>
  )
}
